[tool.poetry]
name = "fantasyfootball"
version = "0.1.0"
description = ""
authors = ["James You"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.3"
bs4 = "^0.0.2"
yahoo-api = "^1.0.1"
ipykernel = "^6.29.5"
yahoo-oauth = "^2.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"